## Settings

# Escape Delay (affects nvim)
set -sg escape-time 10

# change default shell to zsh
set-option -g default-shell /bin/zsh

# terminal colour
set -g default-terminal "tmux-256color"

# enable mouse mode (make windows clickable)
set -g mouse on

# disable automatic renaming
set-option -g allow-rename off

# Autocopy selected text and mouse release
# https://unix.stackexchange.com/questions/348913/copy-selection-to-a-clipboard-in-tmux
set-option -s set-clipboard off
bind-key -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel "xclip -selection clipboard -i"

## Keybinds

unbind C-b
set-option -g prefix C-space
bind-key C-space send-prefix

# create windows splits
bind = split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"
unbind '"'
unbind %

# navigate windows
bind h select-pane -L
bind l select-pane -R
bind k select-pane -U
bind j select-pane -D

# reload config
bind r source-file ~/.tmux.conf

# DESIGN TWEAKS

# don't do anything when a 'bell' rings
set -g visual-activity off
set -g visual-bell off
set -g visual-silence off
setw -g monitor-activity off
set -g bell-action none

# clock mode
setw -g clock-mode-colour green

# copy mode
setw -g mode-style 'fg=black bg=blue bold'

# panes
set -g pane-border-style 'fg=blue'
set -g pane-active-border-style 'fg=green'

# statusbar
set -g status-position bottom
set -g status-justify left
set -g status-style 'fg=blue'

set -g status-left ''
set -g status-left-length 10

set -g status-right-style 'fg=black bg=green'
set -g status-right '%Y-%m-%d %H:%M '
set -g status-right-length 50

setw -g window-status-current-style 'fg=black bg=blue'
setw -g window-status-current-format ' #I #W #F '

setw -g window-status-style 'fg=blue bg=black'
setw -g window-status-format ' #I #[fg=white]#W #[fg=green]#F '

setw -g window-status-bell-style 'fg=green bg=blue bold'

# messages
set -g message-style 'fg=green bg=blue bold'
